package features.auth.view;

import core.BaseApp;
import core.Session;
import features.account.model.Account;
import features.account.view.screens.AccountListScreen;
import features.auth.controller.UserController;
import features.auth.model.User;
import features.kyc.model.KYCDetails;
import features.kyc.view.KYCScreen;
import java.util.List;
import javax.swing.JOptionPane;

public class LoginScreen extends javax.swing.JFrame {
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomebackLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        forgetpasswordLabel = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        donthaveanaccountLabel = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        gettingeasierLabel = new javax.swing.JLabel();
        payforanytransferLabel = new javax.swing.JLabel();
        withnbankLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        welcomebackLabel.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        welcomebackLabel.setText("Hi, Welcome Back ");

        emailLabel.setBackground(new java.awt.Color(102, 102, 102));
        emailLabel.setForeground(new java.awt.Color(102, 102, 102));
        emailLabel.setText(" Email");

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tfEmail.setToolTipText("Enter your email");

        passwordLabel.setForeground(new java.awt.Color(102, 102, 102));
        passwordLabel.setText("Password");

        forgetpasswordLabel.setForeground(new java.awt.Color(255, 102, 0));
        forgetpasswordLabel.setText("Forget Password?");
        forgetpasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onForgotPasswordClick(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 153, 0));
        btnLogin.setText("Sign In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        donthaveanaccountLabel.setText("Don’t Have an Account?");

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        gettingeasierLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gettingeasierLabel.setForeground(new java.awt.Color(255, 255, 255));
        gettingeasierLabel.setText("Getting Easier");

        payforanytransferLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payforanytransferLabel.setForeground(new java.awt.Color(255, 255, 255));
        payforanytransferLabel.setText("Pay For Any Transfer");

        withnbankLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        withnbankLabel.setForeground(new java.awt.Color(255, 153, 0));
        withnbankLabel.setText("with Nbank");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/features/auth/view/assets/Image1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gettingeasierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payforanytransferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withnbankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gettingeasierLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payforanytransferLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withnbankLabel)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Register");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onRegisterClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donthaveanaccountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(welcomebackLabel)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEmail)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                            .addComponent(forgetpasswordLabel))
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(welcomebackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(forgetpasswordLabel))
                .addGap(18, 18, 18)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donthaveanaccountLabel)
                    .addComponent(jLabel12))
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onRegisterClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRegisterClick
        // TODO add your handling code here:
        new RegisterScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_onRegisterClick

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      // TODO add your handling code here:
      String email = tfEmail.getText();
      String password = tfPassword.getText();
      validateAndLogin(email,password);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void onForgotPasswordClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onForgotPasswordClick
        // TODO add your handling code here:
    }//GEN-LAST:event_onForgotPasswordClick
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel donthaveanaccountLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel forgetpasswordLabel;
    private javax.swing.JLabel gettingeasierLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel payforanytransferLabel;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JLabel welcomebackLabel;
    private javax.swing.JLabel withnbankLabel;
    // End of variables declaration//GEN-END:variables

    private void validateAndLogin(String email, String password) {
    // Validate fields
    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Both fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Login logic using UserController
    try {
        UserController userController = BaseApp.getUserController();
        User user = userController.loginUser(email, password);
        if (user != null) {
            // Set the user in the session
            Session currentSession = Session.getSession();
            currentSession.setUserToSession(user);

            // Show success message
            int response = JOptionPane.showConfirmDialog(this, "Login successful!", "Success", JOptionPane.OK_CANCEL_OPTION);

            if (response == JOptionPane.OK_OPTION) {
                // Open AccountScreen and close LoginScreen
                int userId = Session.getSession().getLoggedInUser().getUserId();
                KYCDetails kycDetails = BaseApp.getKycController().getKYCDetailsFromUserId(String.valueOf(userId));
                List<Account> accountList = BaseApp.getAccountController().getAllInactiveUserAccount(userId);
                if(kycDetails == null){
                    new KYCScreen().setVisible(true);
                } if(accountList == null || accountList.isEmpty()){
                    new Dashboard().setVisible(true);
                }else {
                    new AccountListScreen().setVisible(true);
                }
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid email or password!", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }
}
