/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package features.kyc.view;

import core.BaseApp;
import core.CustomDateFormatter;
import core.MessageStringManager;
import core.Session;
import features.auth.model.User;
import features.auth.view.Dashboard;
import features.kyc.model.IdentityType;
import features.kyc.model.KYCDetails;
import features.message.controller.MessageController;
import features.message.model.MessageInfo;
import features.message.model.MessageType;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class KYCScreen extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount1
     */
    public KYCScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoBtnGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        createaccountLabel = new javax.swing.JLabel();
        personalinformationLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        citizenshipnumberLabel = new javax.swing.JLabel();
        tfIdentityNumber = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        rdoNationalID = new javax.swing.JRadioButton();
        rdoPassport = new javax.swing.JRadioButton();
        rdoDL = new javax.swing.JRadioButton();
        nameLabel2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDob1 = new javax.swing.JLabel();
        citizenshipnumberLabel1 = new javax.swing.JLabel();
        dobLabel1 = new javax.swing.JLabel();
        tfIdentityIssueDate = new com.toedter.calendar.JDateChooser();
        personalinformationLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        createaccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createaccountLabel.setForeground(new java.awt.Color(0, 153, 153));
        createaccountLabel.setText("Update Your KYC");

        personalinformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personalinformationLabel.setForeground(new java.awt.Color(0, 102, 102));
        personalinformationLabel.setText("Personal Information");

        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText("Name:");

        addressLabel.setForeground(new java.awt.Color(102, 102, 102));
        addressLabel.setText("Idtentity Type");

        citizenshipnumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        citizenshipnumberLabel.setText("Identity Number");

        btnSubmit.setBackground(new java.awt.Color(255, 153, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        lblName.setText("Kiran Kumar");

        lblDob.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        lblDob.setText("(2001/01/01)");

        nameLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel1.setText("Note: You can request to open Bank Account once KYC is approved.");

        rdoBtnGroup.add(rdoNationalID);
        rdoNationalID.setText("National ID");
        rdoNationalID.setName("NationalID"); // NOI18N
        rdoNationalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNationalIDActionPerformed(evt);
            }
        });

        rdoBtnGroup.add(rdoPassport);
        rdoPassport.setSelected(true);
        rdoPassport.setText("Passport");
        rdoPassport.setName("Passport"); // NOI18N
        rdoPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPassportActionPerformed(evt);
            }
        });

        rdoBtnGroup.add(rdoDL);
        rdoDL.setText("Driving License");
        rdoDL.setName("DrivingLicense"); // NOI18N
        rdoDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDLActionPerformed(evt);
            }
        });

        nameLabel2.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel2.setText("Email:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        lblEmail.setText("Kiran.Kumar@Gmail.com");

        lblDob1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblDob1.setForeground(new java.awt.Color(0, 153, 0));
        lblDob1.setText("(verified)");

        citizenshipnumberLabel1.setForeground(new java.awt.Color(102, 102, 102));
        citizenshipnumberLabel1.setText("Identity Issue Date");

        dobLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dobLabel1.setForeground(new java.awt.Color(255, 51, 51));
        dobLabel1.setText("(In AD)");

        personalinformationLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personalinformationLabel1.setForeground(new java.awt.Color(0, 102, 102));
        personalinformationLabel1.setText("Identity Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDob)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDob1))
                                    .addComponent(personalinformationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 44, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rdoDL)
                                .addGap(26, 26, 26)))
                        .addComponent(rdoNationalID)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoPassport)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(citizenshipnumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(personalinformationLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(citizenshipnumberLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dobLabel1))
                                .addComponent(tfIdentityIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel1)
                                .addGap(25, 25, 25)))
                        .addGap(0, 9, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createaccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(createaccountLabel)
                .addGap(18, 18, 18)
                .addComponent(personalinformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(lblName)
                    .addComponent(lblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel2)
                    .addComponent(lblEmail)
                    .addComponent(lblDob1))
                .addGap(19, 19, 19)
                .addComponent(personalinformationLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoPassport)
                            .addComponent(rdoNationalID)
                            .addComponent(rdoDL))
                        .addGap(19, 19, 19)
                        .addComponent(citizenshipnumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citizenshipnumberLabel1)
                            .addComponent(dobLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdentityIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        IdentityType selectedIdentityType=IdentityType.Passport;
        if(rdoBtnGroup.isSelected(rdoPassport.getModel())){
            selectedIdentityType = IdentityType.Passport;
        } else if(rdoBtnGroup.isSelected(rdoDL.getModel())){
            selectedIdentityType = IdentityType.DrivingLicense;
        } else if(rdoBtnGroup.isSelected(rdoNationalID.getModel())){
        selectedIdentityType = IdentityType.NationalID;
        } else {
        JOptionPane.showMessageDialog(this, "Identification Type!", "Identification Type is required", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
         // Validate fields
    if (tfIdentityIssueDate.getDate()==null || tfIdentityNumber.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Identification Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try{
        int userId = Session.getSession().getLoggedInUser().getUserId();
        String identityType = selectedIdentityType.name();
        String identityNumber = tfIdentityNumber.getText();
        java.sql.Date formattedDate = CustomDateFormatter.convertPickedDateToSQLDate(tfIdentityIssueDate.getDate().toString());
        KYCDetails kYCDetails = new KYCDetails(userId, identityType, identityNumber,formattedDate);
        boolean result = BaseApp.getKycController().submitKYCDetail(kYCDetails);
        if(result){
        int response = JOptionPane.showConfirmDialog(this, "KYC Submitted successful! Do you want to proceed to Dashboard Screen?", "Success", JOptionPane.OK_CANCEL_OPTION);
        MessageInfo message = new MessageInfo(MessageStringManager.KYC_INFO_TITLE,MessageStringManager.KYC_INFO_MESSAGE);
        new MessageController().saveUserMessage(message,MessageType.KYC);
        if (response == JOptionPane.OK_OPTION) {
                    // Open LoginScreen and close RegisterScreen
                    new Dashboard().setVisible(true);
                    dispose();
                }
        }
    } catch(Exception ex){
    ex.printStackTrace();
    }
    String issueDateFormatted = CustomDateFormatter.convertPickedToDateAndFormatted(tfIdentityIssueDate.getDate().toString());
        System.out.println(issueDateFormatted);
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rdoNationalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNationalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNationalIDActionPerformed

    private void rdoPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoPassportActionPerformed

    private void rdoDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDLActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        rdoBtnGroup.add(rdoDL);
        rdoBtnGroup.add(rdoPassport);
        rdoBtnGroup.add(rdoNationalID);
        User user = Session.getSession().getLoggedInUser();
        lblName.setText(user.getName());
        lblEmail.setText(user.getEmail());
        lblDob.setText(String.format("(%s)",user.getDOB()));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KYCScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KYCScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KYCScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KYCScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KYCScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel citizenshipnumberLabel;
    private javax.swing.JLabel citizenshipnumberLabel1;
    private javax.swing.JLabel createaccountLabel;
    private javax.swing.JLabel dobLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel personalinformationLabel;
    private javax.swing.JLabel personalinformationLabel1;
    private javax.swing.ButtonGroup rdoBtnGroup;
    private javax.swing.JRadioButton rdoDL;
    private javax.swing.JRadioButton rdoNationalID;
    private javax.swing.JRadioButton rdoPassport;
    private com.toedter.calendar.JDateChooser tfIdentityIssueDate;
    private javax.swing.JTextField tfIdentityNumber;
    // End of variables declaration//GEN-END:variables
}
