/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package features.account.view.screens;

import core.BaseApp;
import core.MessageStringManager;
import core.Session;
import features.account.controller.AccountController;
import features.account.model.Account;
import features.account.model.AccountStatus;
import features.account.model.AccountType;
import features.auth.model.User;
import features.message.controller.MessageController;
import features.message.model.MessageInfo;
import features.message.model.MessageType;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
/**
 *
 * @author Pratiksha
 */
public class AccountListScreen extends javax.swing.JFrame {

    private Account normalAccount;
    private Account saverAccount;
    private Account loanAccount;

    /**
     * Creates new form AccountListScreen
     */
    public AccountListScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        pInfotitle1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        pInfotitle = new javax.swing.JLabel();
        pInfoLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblACNumN = new javax.swing.JLabel();
        lblAccNameN = new javax.swing.JLabel();
        lblACTypeN = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblBalanceN = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblACNumS = new javax.swing.JLabel();
        lblAccNameS = new javax.swing.JLabel();
        lblACTypeS = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblBalanceS = new javax.swing.JLabel();
        loanAccountPannel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblACNumL = new javax.swing.JLabel();
        lblAccNameL = new javax.swing.JLabel();
        lblACTypeL = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblBalanceL = new javax.swing.JLabel();
        requestLoanAccountPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 510));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 510));

        headerPanel.setBackground(new java.awt.Color(153, 255, 255));
        headerPanel.setName("RequestBankAccountPannel"); // NOI18N

        pInfotitle1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        pInfotitle1.setForeground(new java.awt.Color(0, 0, 204));
        pInfotitle1.setText("BANK MANAGEMENT SYSTEM");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("X");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21onCloseMessageInfo(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI Semilight", 3, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 204));
        lblName.setText("Admin V");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(pInfotitle1)
                .addGap(102, 102, 102)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pInfotitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addComponent(lblName))
                .addContainerGap())
        );

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setName("RequestBankAccountPannel"); // NOI18N

        pInfotitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pInfotitle.setText("Panel Info");

        pInfoLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pInfoLabel.setForeground(new java.awt.Color(51, 0, 255));
        pInfoLabel.setText("Panel Message");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8onCloseMessageInfo(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(pInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(pInfotitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pInfotitle)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInfoLabel))
        );

        accountPanel.setBackground(new java.awt.Color(255, 255, 255));
        accountPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Your Bank Accounts");

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickNormalAccount(evt);
            }
        });

        jLabel5.setText("Amount Number:");

        jLabel9.setText("Account Name:");

        jLabel10.setText("Amount:");

        lblACNumN.setText("1234567890123456");

        lblAccNameN.setText("Kiran Kumar");

        lblACTypeN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblACTypeN.setText("Normal Account");

        jLabel16.setText("Rs.");

        lblBalanceN.setText("123456");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblACTypeN)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalanceN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAccNameN))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblACNumN)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblAccNameN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblACNumN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(lblBalanceN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblACTypeN)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickSaverAccount(evt);
            }
        });

        jLabel6.setText("Amount Number:");

        jLabel11.setText("Account Name:");

        jLabel12.setText("Amount:");

        lblACNumS.setText("12345678901234S");

        lblAccNameS.setText("Kiran Kumar");

        lblACTypeS.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblACTypeS.setText("Normal Account");

        jLabel18.setText("Rs.");

        lblBalanceS.setText("12345678");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblACTypeS)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalanceS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAccNameS))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblACNumS)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblAccNameS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblACNumS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(lblBalanceS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblACTypeS)
                .addContainerGap())
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loanAccountPannel.setBackground(new java.awt.Color(255, 255, 255));
        loanAccountPannel.setPreferredSize(new java.awt.Dimension(300, 100));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickLoanAccount(evt);
            }
        });

        jLabel7.setText("Amount Number:");

        jLabel13.setText("Account Name:");

        jLabel19.setText("Amount:");

        lblACNumL.setText("12345678901234L");

        lblAccNameL.setText("Kiran Kumar");

        lblACTypeL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblACTypeL.setText("Normal Account");

        jLabel20.setText("Rs.");

        lblBalanceL.setText("1234567");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblACTypeL)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalanceL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAccNameL))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblACNumL)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblAccNameL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblACNumL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(lblBalanceL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblACTypeL))
        );

        requestLoanAccountPanel.setBackground(new java.awt.Color(255, 255, 255));
        requestLoanAccountPanel.setName("RequestBankAccountPannel"); // NOI18N
        requestLoanAccountPanel.setPreferredSize(new java.awt.Dimension(300, 55));

        jLabel14.setText("Request to open a loan account?");

        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("Request Here");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15onRequestToOpenLoanAccount(evt);
            }
        });

        javax.swing.GroupLayout requestLoanAccountPanelLayout = new javax.swing.GroupLayout(requestLoanAccountPanel);
        requestLoanAccountPanel.setLayout(requestLoanAccountPanelLayout);
        requestLoanAccountPanelLayout.setHorizontalGroup(
            requestLoanAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestLoanAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        requestLoanAccountPanelLayout.setVerticalGroup(
            requestLoanAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestLoanAccountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(requestLoanAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel17.setText("Your Loan Accounts");

        javax.swing.GroupLayout loanAccountPannelLayout = new javax.swing.GroupLayout(loanAccountPannel);
        loanAccountPannel.setLayout(loanAccountPannelLayout);
        loanAccountPannelLayout.setHorizontalGroup(
            loanAccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanAccountPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loanAccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loanAccountPannelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(425, 425, 425))
                    .addGroup(loanAccountPannelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loanAccountPannelLayout.createSequentialGroup()
                        .addComponent(requestLoanAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        loanAccountPannelLayout.setVerticalGroup(
            loanAccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loanAccountPannelLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestLoanAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loanAccountPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanAccountPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15onRequestToOpenLoanAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15onRequestToOpenLoanAccount
        // TODO add your handling code here:
        String loanAmount = JOptionPane.showInputDialog(null, "Enter the Loan Amount to be request", "Request Loan Account Opening", JOptionPane.INFORMATION_MESSAGE);
        // Open AccountScreen and close LoginScreen
        int userId = Session.getSession().getLoggedInUser().getUserId();
        boolean result = BaseApp.getAccountController().openLoanAccount(userId,Integer.parseInt(loanAmount));
        if(result){
            JOptionPane.showMessageDialog(null, "You request to open loan account has received!", "Request Received", JOptionPane.INFORMATION_MESSAGE);
            infoPanel.setVisible(true);
            MessageInfo message = new MessageInfo(MessageStringManager.LOAN_ACCOUNT_OPENED_INFO_TITLE, MessageStringManager.LOAN_ACCOUNT_OPENED_INFO_MESSAGE);
            new MessageController().deleteUserMessage();
            new MessageController().saveUserMessage(message,MessageType.LOAN);
            requestLoanAccountPanel.setVisible(false);
        }
    }//GEN-LAST:event_jLabel15onRequestToOpenLoanAccount

    private void onClickNormalAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickNormalAccount
        // TODO add your handling code here:
        new AccountDetailScreen(normalAccount.getAccountId()).setVisible(true);
        
    }//GEN-LAST:event_onClickNormalAccount

    private void onClickSaverAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickSaverAccount
        // TODO add your handling code here:
        new AccountDetailScreen(saverAccount.getAccountId()).setVisible(true);
        
    }//GEN-LAST:event_onClickSaverAccount

    private void onClickLoanAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickLoanAccount
        // TODO add your handling code here:
        new AccountDetailScreen(loanAccount.getAccountId()).setVisible(true);
    }//GEN-LAST:event_onClickLoanAccount

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        User LoggedInUser = Session.getSession().getLoggedInUser();
        
        infoPanel.setVisible(false);
        accountPanel.setVisible(false);
        loanAccountPannel.setVisible(false);
        requestLoanAccountPanel.setVisible(false);
        
        String firstName = LoggedInUser.getName().split(" ")[0];
        lblName.setText(firstName);
        // get ALl user Active Account
        fetchedALlUserActiveAccount(LoggedInUser);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel8onCloseMessageInfo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8onCloseMessageInfo
        // TODO add your handling code here:
        infoPanel.setVisible(false);
    }//GEN-LAST:event_jLabel8onCloseMessageInfo

    private void jLabel21onCloseMessageInfo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21onCloseMessageInfo
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21onCloseMessageInfo

    void fetchedALlUserActiveAccount(User user){
        AccountController accountController = BaseApp.getAccountController();
                List<Account> accountList = accountController.getAllActiveUserAccount(user.getUserId())
                .stream()
                .filter(account -> (AccountType.NORMAL.name().equalsIgnoreCase(account.getAccountType()) || AccountType.SAVER.name().equalsIgnoreCase(account.getAccountType())))
                .collect(Collectors.toList());
        
        loanAccount = accountController.getAllUserAccount(user.getUserId())
                .stream()
                .filter(account -> (AccountType.LOAN.name().equalsIgnoreCase(account.getAccountType())))
                .collect(Collectors.toList()).getFirst();
        
        
        if(loanAccount != null){
            if(loanAccount.getStatus().equalsIgnoreCase(AccountStatus.ACTIVE.name())) {
                showLoanAccountDesign(loanAccount);
            } else {
                MessageInfo message = getLatestMessage();
                pInfotitle.setText(message.getTitle());
                pInfoLabel.setText(message.getMessage());
                infoPanel.setVisible(true);
                requestLoanAccountPanel.setVisible(false);
            } 
        } else {
            requestLoanAccountPanel.setVisible(true);
        }
        if(!accountList.isEmpty()){
            normalAccount = accountList.stream()
                .filter(account -> AccountType.NORMAL.name().equalsIgnoreCase(account.getAccountType()))
                .collect(Collectors.toList()).getFirst();
            
            
            saverAccount = accountList.stream()
                .filter(account -> AccountType.SAVER.name().equalsIgnoreCase(account.getAccountType()))
                .collect(Collectors.toList()).getFirst();
            
            showAccountsDesign(normalAccount,saverAccount);
        } else {
            MessageInfo message = getLatestMessage();
            pInfotitle.setText(message.getTitle());
            pInfoLabel.setText(message.getMessage());
            infoPanel.setVisible(true);  
        }
    }

    public void showAccountsDesign(Account normalAccount,Account saverAccount){
        accountPanel.setVisible(true);
        String fullname = Session.getSession().getLoggedInUser().getName();

        // For Normal Account
        lblAccNameN.setText(fullname);
        lblACNumN.setText(normalAccount.getAccountNumber());
        lblBalanceN.setText(String.valueOf(normalAccount.getBalance()));
        lblACTypeN.setText(String.format("%s Account", normalAccount.getAccountType()).toUpperCase());

        // For Saver Account
        lblAccNameS.setText(fullname);
        lblACNumS.setText(saverAccount.getAccountNumber());
        lblBalanceS.setText(String.valueOf(saverAccount.getBalance()));
        lblACTypeS.setText(String.format("%s Account", saverAccount.getAccountType()).toUpperCase());
    }

    public void showLoanAccountDesign(Account loanAccount){
        loanAccountPannel.setVisible(true);
        String fullname = Session.getSession().getLoggedInUser().getName();
        // For Normal Account
        lblAccNameL.setText(fullname);
        lblACNumL.setText(loanAccount.getAccountNumber());
        lblBalanceL.setText(String.format("%d", loanAccount.getBalance()));
        lblACTypeL.setText(String.format("%s Account", loanAccount.getAccountType()).toUpperCase());
    }

        
    public MessageInfo getLatestMessage(){
        MessageController messageController = BaseApp.getMessageController();
        return messageController.getUserLastMessage();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountListScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblACNumL;
    private javax.swing.JLabel lblACNumN;
    private javax.swing.JLabel lblACNumS;
    private javax.swing.JLabel lblACTypeL;
    private javax.swing.JLabel lblACTypeN;
    private javax.swing.JLabel lblACTypeS;
    private javax.swing.JLabel lblAccNameL;
    private javax.swing.JLabel lblAccNameN;
    private javax.swing.JLabel lblAccNameS;
    private javax.swing.JLabel lblBalanceL;
    private javax.swing.JLabel lblBalanceN;
    private javax.swing.JLabel lblBalanceS;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel loanAccountPannel;
    private javax.swing.JLabel pInfoLabel;
    private javax.swing.JLabel pInfotitle;
    private javax.swing.JLabel pInfotitle1;
    private javax.swing.JPanel requestLoanAccountPanel;
    // End of variables declaration//GEN-END:variables
}
