package features.account.view.screens;

import core.BaseApp;
import features.account.controller.AccountController;
import features.account.model.Account;
import features.account.model.AccountStatus;
import features.account.model.AccountType;
import features.auth.controller.UserController;
import features.auth.model.User;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pratiksha
 */
public class GetAllAccount extends javax.swing.JFrame {

    /**
     * Creates new form GetAllUser
     */
    public GetAllAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        pInfotitle1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblAccId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfAccBalance = new javax.swing.JTextField();
        cbAccType = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        cbAccStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lblAccNum = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        loanReqPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfLoanReqAmount = new javax.swing.JTextField();
        lblFullName1 = new javax.swing.JLabel();
        lblLoanSuggestedBalance = new javax.swing.JLabel();
        lblFullName3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        headerPanel.setBackground(new java.awt.Color(153, 255, 255));
        headerPanel.setName("RequestBankAccountPannel"); // NOI18N

        pInfotitle1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        pInfotitle1.setForeground(new java.awt.Color(0, 0, 204));
        pInfotitle1.setText("BANK MANAGEMENT SYSTEM");

        lblName.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 204));
        lblName.setText("Admin");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-25.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onBackClick(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pInfotitle1)
                .addGap(254, 254, 254)
                .addComponent(lblName)
                .addGap(28, 28, 28))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pInfotitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblName)))
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(255, 255, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("User Information");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Phone:");

        tblAccount.setBackground(new java.awt.Color(204, 255, 204));
        tblAccount.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Account ID", "User ID", "Account Number", "Available Balance", "Account Type", "Account Status"
            }
        ));
        tblAccount.setGridColor(new java.awt.Color(51, 51, 255));
        tblAccount.setShowGrid(true);
        tblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSelectRow(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccount);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("User ID:");

        lblAccId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAccId.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Search");

        tfSearch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Account Information");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Account ID:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Account Type:");

        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Account Status:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Available Balance:");

        tfAccBalance.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        cbAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Saver", "Loan" }));
        cbAccType.setEnabled(false);

        jSeparator2.setForeground(new java.awt.Color(0, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 51));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Full Name:");

        lblUserId.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(204, 0, 204));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(204, 0, 204));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 0, 204));

        jSeparator4.setForeground(new java.awt.Color(0, 255, 255));

        cbAccStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "In-Active", "Closed" }));
        cbAccStatus.setSelectedIndex(2);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Account Number:");

        lblAccNum.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAccNum.setForeground(new java.awt.Color(0, 0, 204));
        lblAccNum.setText("0");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(204, 0, 204));

        loanReqPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Requested Amount:");

        tfLoanReqAmount.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        lblFullName1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFullName1.setForeground(new java.awt.Color(0, 0, 153));
        lblFullName1.setText("( Suggested Loan Balance: Rs.");

        lblLoanSuggestedBalance.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLoanSuggestedBalance.setForeground(new java.awt.Color(0, 0, 153));
        lblLoanSuggestedBalance.setText("200");

        lblFullName3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFullName3.setForeground(new java.awt.Color(0, 0, 153));
        lblFullName3.setText(")");

        javax.swing.GroupLayout loanReqPanelLayout = new javax.swing.GroupLayout(loanReqPanel);
        loanReqPanel.setLayout(loanReqPanelLayout);
        loanReqPanelLayout.setHorizontalGroup(
            loanReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanReqPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addComponent(tfLoanReqAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loanReqPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFullName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoanSuggestedBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullName3)
                .addGap(64, 64, 64))
        );
        loanReqPanelLayout.setVerticalGroup(
            loanReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanReqPanelLayout.createSequentialGroup()
                .addGroup(loanReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoanReqAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loanReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoanSuggestedBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFullName3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(149, 153, Short.MAX_VALUE))))
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAccId))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(btnUpdate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(btnDelete))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbAccStatus, 0, 110, Short.MAX_VALUE)
                            .addComponent(cbAccType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(30, 30, 30)
                                .addComponent(tfAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(loanReqPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccId)
                    .addComponent(jLabel9)
                    .addComponent(lblAccNum)
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAccStatus)
                        .addComponent(jLabel12))
                    .addComponent(loanReqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))))
                    .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loanReqPanel.setVisible(false);
        getAllAccountTableData();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        AccountController accountController = BaseApp.getAccountController();
        AccountStatus accountStatus = AccountStatus.CLOSED;
//        boolean isVerified = false;
        if(tblAccount.getSelectedRowCount()==1){
            int selectedRow = tblAccount.getSelectedRow();
            String accountId = tblAccount.getValueAt(selectedRow, 0).toString();
            String userId = tblAccount.getValueAt(selectedRow, 1).toString();
            String accountNumber = tblAccount.getValueAt(selectedRow, 2).toString();
            String accountBalance = tblAccount.getValueAt(selectedRow, 3).toString();
            String accountType = tblAccount.getValueAt(selectedRow, 4).toString();
            String currentAccountStatus = tblAccount.getValueAt(selectedRow, 5).toString();
            
            if(accountType.equalsIgnoreCase(AccountType.LOAN.name()) && currentAccountStatus.equalsIgnoreCase(AccountStatus.INACTIVE.name())){
                loanReqPanel.setVisible(true);
                tfAccBalance.setEnabled(false);
            } else {
                tfAccBalance.setEnabled(true);
            }
            String reqAmount = tfLoanReqAmount.getText();
            String tfBalance = tfAccBalance.getText();
            
            int newAccStatus = cbAccStatus.getSelectedIndex();
            if(newAccStatus == 0){
                accountStatus = AccountStatus.ACTIVE; 
            } else if(newAccStatus == 1){
                accountStatus = AccountStatus.INACTIVE; 
            }else {
                accountStatus = AccountStatus.CLOSED;
            }
            
            if(accountStatus == AccountStatus.CLOSED){
                JOptionPane.showMessageDialog(this, "Please visit your nearest branch for closing account.");
                return;
            }
            if(accountStatus == AccountStatus.INACTIVE && accountBalance.equals(tfBalance)){
                JOptionPane.showMessageDialog(this, "Failed to update the status to inactive.");
                return;
            }
            boolean result = false;
            try {
                if(accountStatus == AccountStatus.ACTIVE && !accountType.equalsIgnoreCase(AccountType.LOAN.name()) && accountBalance.equals(tfBalance)){
                    accountController.approveAccountOpeningRequest(Integer.parseInt(userId));
                } else if(accountStatus == AccountStatus.ACTIVE && !accountType.equalsIgnoreCase(AccountType.LOAN.name()) && !accountBalance.equals(tfBalance)){
                    accountController.updateAccountBalance(accountNumber,-Double.parseDouble(accountBalance));
                    accountController.updateAccountBalance(accountNumber,Double.parseDouble(tfBalance));
                } else if(accountStatus == AccountStatus.ACTIVE && accountType.equalsIgnoreCase(AccountType.LOAN.name())){
                    
                    accountController.approveLoanAccountOpeningRequest(Integer.parseInt(userId));
                    // Set inital balance to zero
                    accountController.updateAccountBalance(accountNumber,-Double.parseDouble(accountBalance));
                    accountController.updateAccountBalance(accountNumber,-Double.parseDouble(tfLoanReqAmount.getText()));
                }
                result=true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "An Unknown error occur");
                result = false;
                return;
            }
            
            if(result){
                JOptionPane.showMessageDialog(this, "Account Details are up-to-date now");
                tblAccount.repaint();
                tblAccount.validate();
                getAllAccountTableData();
                lblAccId.setText("");
                lblAccNum.setText("");
                tfLoanReqAmount.setText("");
                lblLoanSuggestedBalance.setText("0");
                tfAccBalance.setText("");
                loanReqPanel.setVisible(false);
                
                // set user details empty textfield
                lblEmail.setText("");
                lblFullName.setText("");
                lblPhone.setText("");
                lblUserId.setText("");
           } else {
                JOptionPane.showMessageDialog(this, "Failed to update Account Detail");
            }
        } else {
        if(tblAccount.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            JOptionPane.showMessageDialog(this, "Please Select Single row for update");
           }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String searchCharacter = tfSearch.getText();
        searchAndFilter(searchCharacter);
    }//GEN-LAST:event_tfSearchKeyReleased

    private void onSelectRow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSelectRow
        // TODO add your handling code here:
        if(tblAccount.getSelectedRowCount()==1){
            int selectedRow = tblAccount.getSelectedRow();
            String accountId = tblAccount.getValueAt(selectedRow, 0).toString();
            String userId = tblAccount.getValueAt(selectedRow, 1).toString();
            String accountNumber = tblAccount.getValueAt(selectedRow, 2).toString();
            String accountBalance = tblAccount.getValueAt(selectedRow, 3).toString();
            String accountType = tblAccount.getValueAt(selectedRow, 4).toString();
            String currentAccountStatus = tblAccount.getValueAt(selectedRow, 5).toString();

            // Now setText
            lblAccId.setText(accountId);
            lblAccNum.setText(accountNumber);
            
            if(accountType.equalsIgnoreCase(AccountType.LOAN.name()) && currentAccountStatus.equalsIgnoreCase(AccountStatus.INACTIVE.name())){
                tfAccBalance.setText("0");
                tfAccBalance.setEnabled(false);
                tfLoanReqAmount.setEnabled(true);
                tfLoanReqAmount.setText(accountBalance);
                String loanSuggestedBalance = getLoanSuggestedBalance(userId);
                lblLoanSuggestedBalance.setText(loanSuggestedBalance);
                loanReqPanel.setVisible(true);
            } else if(accountType.equalsIgnoreCase(AccountType.LOAN.name()) && currentAccountStatus.equalsIgnoreCase(AccountStatus.ACTIVE.name())){
                tfAccBalance.setText(accountBalance);
                tfAccBalance.setEnabled(true);
                tfLoanReqAmount.setText("0");
                tfLoanReqAmount.setEnabled(false);
                lblLoanSuggestedBalance.setText("0");
                loanReqPanel.setVisible(false);
            } else if(!accountType.equalsIgnoreCase(AccountType.LOAN.name()) && currentAccountStatus.equalsIgnoreCase(AccountStatus.ACTIVE.name())){
                tfAccBalance.setText(accountBalance);
                tfAccBalance.setEnabled(true);
                tfLoanReqAmount.setText("0");
                tfLoanReqAmount.setEnabled(false);
                lblLoanSuggestedBalance.setText("0");
                loanReqPanel.setVisible(false);
            }
            
            if(accountType.equalsIgnoreCase(AccountType.NORMAL.name())){
                cbAccType.setSelectedIndex(0);
            } else if(accountType.equalsIgnoreCase(AccountType.SAVER.name())){
                cbAccType.setSelectedIndex(1);
            } else {
                cbAccType.setSelectedIndex(2);
            }
            
            if(currentAccountStatus.equalsIgnoreCase(AccountStatus.ACTIVE.name())){
                cbAccStatus.setSelectedIndex(0);
            } else if(currentAccountStatus.equalsIgnoreCase(AccountStatus.INACTIVE.name())){
                cbAccStatus.setSelectedIndex(1);
            } else {
                cbAccStatus.setSelectedIndex(2);
            }
            
            setUserDetails(userId);

        } else {
            if(tblAccount.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please Select Single row for update");
            }
        }

    }//GEN-LAST:event_onSelectRow

    private String getLoanSuggestedBalance(String userId){
        UserController uc = BaseApp.getUserController();
        int points = uc.getUserDetails(Integer.parseInt(userId)).getPoints();
        return String.valueOf(calculateAndSuggestLoanAmount(points));
    }
    private double calculateAndSuggestLoanAmount(int points){
        if(points <100){
            return 1000;
        }else if(points <500){
            return 5000;
        } else if(points <1000){
            return 10000;
        } else if(points <2000){
            return 20000;
        } else if(points <5000){
            return 50000;
        } else {
            return 100000;
        }
    }
    
    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void onBackClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBackClick
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_onBackClick

   //
    
    private void searchAndFilter(String searchText){
       DefaultTableModel userTable = (DefaultTableModel) tblAccount.getModel();
       TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(userTable);
       tblAccount.setRowSorter(tableRowSorter);
       tableRowSorter.setRowFilter(RowFilter.regexFilter(searchText));
   }
    private void setUserDetails(String userId){
        UserController uc = BaseApp.getUserController();
        User user = uc.getUserDetails(Integer.parseInt(userId));
        lblUserId.setText(userId);
        lblFullName.setText(user.getName());
        lblPhone.setText(user.getPhone());
        lblEmail.setText(user.getEmail());
    }

    private void getAllAccountTableData() {
        AccountController accountController = BaseApp.getAccountController();
        List<Account> accountList = accountController.getAllAccount();
        DefaultTableModel accountTable = (DefaultTableModel) tblAccount.getModel();

        // Clear existing rows
        accountTable.setRowCount(0);

        for (Account account : accountList) {
            // Retrieve transaction details with fallbacks for null or empty values
            String userId = String.valueOf(account.getUserId());
            String accountId = String.valueOf(account.getAccountId());
            String accountNumber = account.getAccountNumber();
            String balance = String.valueOf(account.getBalance());
            String accountType = account.getAccountType();
            String accountStatus = account.getStatus();
           
            // Add a row to the table
            accountTable.addRow(new Object[] { accountId, userId, accountNumber,balance,accountType,accountStatus});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetAllAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetAllAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetAllAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetAllAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetAllAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAccStatus;
    private javax.swing.JComboBox<String> cbAccType;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAccId;
    private javax.swing.JLabel lblAccNum;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblFullName1;
    private javax.swing.JLabel lblFullName3;
    private javax.swing.JLabel lblLoanSuggestedBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JPanel loanReqPanel;
    private javax.swing.JLabel pInfotitle1;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField tfAccBalance;
    private javax.swing.JTextField tfLoanReqAmount;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
